# Generated by Django 2.2.3 on 2019-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionNumber', models.IntegerField()),
                ('releaseNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CyclparkPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.IntegerField(default=None, unique=True, verbose_name='global_id')),
                ('name', models.CharField(default=None, max_length=200, verbose_name='Name')),
                ('admarea', models.CharField(default=None, max_length=200, verbose_name='Adm. area')),
                ('district', models.CharField(default=None, max_length=200, verbose_name='District')),
                ('address', models.CharField(default=None, max_length=200, verbose_name='Address')),
                ('capacity', models.IntegerField(default=None, verbose_name='Capacity')),
                ('departamentalaffiliation', models.CharField(default=None, max_length=200, verbose_name='Departament Affiliation')),
                ('objectoperorgname', models.CharField(default=None, max_length=200, verbose_name='Object organisation name')),
                ('longitude_WGS84', models.FloatField(default=None, verbose_name='Langitude')),
                ('latitude_WGS84', models.FloatField(default=None, verbose_name='Latitude')),
            ],
        ),
    ]
